---
# User Configuration
ansible_user: "{{ ansible_user_id | default(lookup('env', 'USER')) }}"
ansible_user_dir: "/home/{{ ansible_user }}"

# Path Configuration
config_dir: "{{ ansible_user_dir }}/.config"
backup_dir: "{{ ansible_user_dir }}/.config_backup"
theme_dir: "{{ ansible_user_dir }}/.themes"
script_dir: "{{ ansible_user_dir }}/.local/share/bin"

# Hyprland Configuration
hyprland:
  script_path: "{{ script_dir }}"
  monitor_config: ",1920x1080@60,auto,1"
  bluetooth_enabled: true
  night_light_enabled: true
  night_light_temp: 4500
  gdk_scale: 1
  keyboard_layout: "us"
  follow_mouse: 1
  natural_scroll: false
  mouse_sensitivity: 0
  mouse_no_accel: true
  numlock_default: true
  custom_mouse_settings: true
  custom_mouse_name: "epic mouse V1"
  custom_mouse_sensitivity: -0.5
  workspace_swipe: true
  workspace_swipe_fingers: 5
  pseudotile: true
  preserve_split: true
  master_new_status: "master"
  vrr: 0
  disable_logo: true
  disable_splash: true
  force_default_wallpaper: 0
  xwayland_zero_scaling: true

# Package Lists (Conflict-Free)
packages:
  base:
    - base-devel
    - git
    - python-pip

  hyprland:
    - hyprland
    - waybar
    - rofi-wayland
    - dunst
    - swaybg
    - swayidle
    - wlogout
    - xdg-desktop-portal-hyprland
    - xdg-desktop-portal-gtk
    - qt5-wayland
    - qt6-wayland
    - qt5ct
    - qt6ct
    - hyprpaper
    - hyprpicker
    - hyprshot
    - hyprlock
    - hypridle

  display:
    - mesa
    - vulkan-intel
    - vulkan-radeon
    - libva-intel-driver
    - libva-mesa-driver
    - vulkan-icd-loader
    - lib32-vulkan-icd-loader

  audio:
    - pipewire
    - pipewire-alsa
    - pipewire-pulse
    - pipewire-jack
    - wireplumber
    - pavucontrol
    - pamixer
    - alsa-utils

  utilities:
    - libinput
    - brightnessctl
    - wl-clipboard
    - grim
    - slurp
    - swappy
    - cliphist
    - wf-recorder
    - polkit-kde-agent
    - udiskie
    - network-manager-applet
    - blueman
    - bluez
    - bluez-utils

  fonts:
    - ttf-jetbrains-mono
    - ttf-font-awesome
    - noto-fonts
    - noto-fonts-emoji
    - ttf-nerd-fonts-symbols
    - ttf-fira-code

  terminal:
    - kitty
    - foot
    - zsh
    - tmux
    - neovim
    - fish

  aur:
    - yay
    - brave-bin
    - wlogout-emoji-git
    - hyprpm
    - hyprland-nvidia

# Optional Features
features:
  enable_bluetooth: true
  enable_printing: false
  enable_flatpak: true
  enable_docker: false
