---
# apps.yml - Install/remove applications for HollowDots setup

- name: Remove conflicting packages
  become: yes
  pacman:
    name: "{{ item }}"
    state: absent
    recurse: yes
  loop:
    - qbittorrent # replaced by qbittorrent-enhanced
    - code # replaced by visual-studio-code-bin
    - mpv # conflict with mpv-git
    - mpv-git # conflict with mpv
    - vesktop # conflict with vesktop-bin
  failed_when: false
  tags:
    - essentials
    - install
    - pacman

# -----------------------------
# Official pacman repository apps
# -----------------------------
- name: Install essential applications from pacman
  become: yes
  pacman:
    name:
      - telegram-desktop
      - yt-dlp
      - flatpak
      - aria2
      - auto-cpufreq
      - appimagelauncher
      - btop
      - htop
      - lm_sensors
      - inxi
      - fastfetch
      - gparted
      - hugo
      - jdk-openjdk
      - nvtop
      - onedrive-abraunegg
      - stremio
      - tailscale
      - p7zip
      - uwufetch
      - zoom
      - ncdu
      - obsidian
      - thunar
      - ffmpeg
      - deadbeef
      - imagemagick
      - gimp
      - imv
      - libreoffice-fresh
      - element-desktop
      - bc
      - dolphin
      - libnotify
      - v4l-utils
      - ydotool
      - pciutils
      - socat
      - cowsay
      - lshw
      - swappy
      - playerctl
      - ventoy
    state: present
  tags:
    - essentials
    - install
    - pacman

# -----------------------------
# AUR/Chaotic packages
# -----------------------------
- name: Install AUR/Chaotic applications
  become: yes
  pacman:
    name:
      - anydesk-bin
      - qbittorrent-enhanced
      - cloudflare-warp-bin
      - youtube-music-bin
      - chaotic-aur/rustdesk-bin
      - vesktop-bin
    state: present
  tags:
    - essentials
    - install
    - aur
