- name: Install yay dependencies
  become: yes
  pacman:
    name:
      - go
      - fakeroot
    state: present
  tags:
    - dotfiles
    - install
    - aur
    - yay

- name: Remove yay clone directory if it exists
  become: true
  ansible.builtin.file:
    path: /tmp/yay
    state: absent
  tags:
    - dotfiles
    - install
    - aur
    - yay

- name: Clone yay repository from AUR
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay
  tags:
    - dotfiles
    - install
    - aur
    - yay

- name: Build yay
  command: makepkg -f --noconfirm
  args:
    chdir: /tmp/yay
  tags:
    - dotfiles
    - install
    - aur
    - yay

- name: Find the yay package
  find:
    paths: /tmp/yay
    patterns: "yay-*.pkg.tar.zst"
  register: yay_package
  tags:
    - dotfiles
    - install
    - aur
    - yay

- name: Install yay
  become: yes
  command: pacman -U --noconfirm {{ yay_package.files[0].path }}
  tags:
    - dotfiles
    - install
    - aur
    - yay